#!/usr/bin/env bash

trap 'pkill -P $$' EXIT

if [[ ! $# -eq 1 ]]; then
    echo "Usage: $0 <JOBS>"
    exit 1
fi

for _ in $(seq 1 "$1"); do
    (
        set -e
        iter=0

        while true;
        do
            iter=$((iter + 1))

            /usr/bin/clang++ -w -stdlib=libc++ -std=c++26 \
                -march=native -O3 -ffast-math             \
                -fno-crash-diagnostics                    \
                -o /dev/null -c Foo.cppm                  \
                || { echo "Crashed on the $iter-th try"; exit 1; }
        done
    ) &
done

wait -n

exit $?
